"""empty message

Revision ID: 41084a944409
Revises: afbf0bae9d6e
Create Date: 2024-05-14 13:44:31.965339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41084a944409'
down_revision = 'afbf0bae9d6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cobertura_img', sa.LargeBinary(), nullable=True))
        batch_op.drop_column('cobertura_img_')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cobertura_img_', sa.BLOB(), nullable=True))
        batch_op.drop_column('cobertura_img')

    # ### end Alembic commands ###
