"""empty message

Revision ID: 4d5065a12a57
Revises: b9c63a12ffc1
Create Date: 2024-05-08 12:16:56.710801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d5065a12a57'
down_revision = 'b9c63a12ffc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('antenna_direction', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('antenna_tilt', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('antenna_tilt')
        batch_op.drop_column('antenna_direction')

    # ### end Alembic commands ###
