"""empty message

Revision ID: 4f65fed2f5a5
Revises: caf3c010faf5
Create Date: 2024-05-21 18:38:31.134980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f65fed2f5a5'
down_revision = 'caf3c010faf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('antenna_pattern_data_h', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('antenna_pattern_data_v', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('antenna_pattern_data_h_modified', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('antenna_pattern_data_v_modified', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('antenna_pattern_data_v_modified')
        batch_op.drop_column('antenna_pattern_data_h_modified')
        batch_op.drop_column('antenna_pattern_data_v')
        batch_op.drop_column('antenna_pattern_data_h')

    # ### end Alembic commands ###
