"""Initial migration.

Revision ID: a0e2b314ab99
Revises: 
Create Date: 2024-04-17 19:19:50.320233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0e2b314ab99'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('propagation_model', sa.String(), nullable=True),
    sa.Column('frequencia', sa.Float(), nullable=True),
    sa.Column('tower_height', sa.Float(), nullable=True),
    sa.Column('cable_type', sa.String(), nullable=True),
    sa.Column('transmission_power', sa.Float(), nullable=True),
    sa.Column('antenna_gain', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('servico', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
