"""empty message

Revision ID: afbf0bae9d6e
Revises: 4d5065a12a57
Create Date: 2024-05-14 13:05:24.362354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afbf0bae9d6e'
down_revision = '4d5065a12a57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('antenna_pattern_img_dia_H', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('antenna_pattern_img_dia_V', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('cobertura_img_', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('perfil_img', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('perfil_img')
        batch_op.drop_column('cobertura_img_')
        batch_op.drop_column('antenna_pattern_img_dia_V')
        batch_op.drop_column('antenna_pattern_img_dia_H')

    # ### end Alembic commands ###
