"""empty message

Revision ID: b1f7caa0b9a0
Revises: a0e2b314ab99
Create Date: 2024-04-28 18:35:02.707090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1f7caa0b9a0'
down_revision = 'a0e2b314ab99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_loss', sa.Float(), nullable=True))
        batch_op.drop_column('cable_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cable_type', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('total_loss')

    # ### end Alembic commands ###
